language: node_js
node_js:
  - "0.10"

before_install:
  - "curl -L http://git.io/3l-rRA | /bin/sh"
  - "npm install -g meteorite"
  - "mrt add collection-api"

services:
  - mongodb
env:
  - LAIKA_OPTIONS="-t 5000"
